# Generated by Django 5.1 on 2025-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
