# Generated by Django 5.1 on 2025-01-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_b64',
            new_name='image',
        ),
    ]
